
#ifndef _CTWS_DEF_H_
#define _CTWS_DEF_H_

#define LEAD_CHOICE     0x01
#define ENTRY_CHANGE    0x02
#define CHANGE_CHOICE   0x03
#define ABORT_CHANGE    0x04
#define ACCEPT_ENTRY    0x05
#define CHANGED_OVER    0x06
#define START_DIVERT    0x07
#define READY_DIVERT    0x08
#define DIVERT_CALLS    0x09
#define DIVERT_DONE     0x0A
#define DIVERT_ACKED    0x0B
#define DIVERT_ACCEPT   0x0C
#define ABORT_DIVERT    0x0D
#define CHOICE_ASSIGN   0x0E
#define EXIT_CHOICE     0x0F
#define ABORT_CHOICE    0x10
#define EXIT_ACCEPTED   0x11
#define CHOICE_DONE     0x12

#endif

