
#ifndef _KEYBOARD_H_
#define _KEYBOARD_H_

#define ESC             0x001B

#define F1              0x3B00
#define F2              0x3C00
#define F3              0x3D00
#define F4              0x3E00
#define F5              0x3F00
#define F6              0x4000
#define F7              0x4100
#define F8              0x4200
#define F9              0x4300
#define F10             0x4400
#define F11             0x8500
#define F12             0x8600

#define CTL_F1          0x5E00
#define CTL_F2          0x5F00
#define CTL_F3          0x6000
#define CTL_F4          0x6100
#define CTL_F5          0x6200
#define CTL_F6          0x6300
#define CTL_F7          0x6400
#define CTL_F8          0x6500
#define CTL_F9          0x6600
#define CTL_F10         0x6700
#define CTL_F11         0x8900
#define CTL_F12         0x8A00

#define ALT_F1          0x6800
#define ALT_F2          0x6900
#define ALT_F3          0x6A00
#define ALT_F4          0x6B00
#define ALT_F5          0x6C00
#define ALT_F6          0x6D00
#define ALT_F7          0x6E00
#define ALT_F8          0x6F00
#define ALT_F9          0x7000
#define ALT_F10         0x7100
#define ALT_F11         0x8B00
#define ALT_F12         0x8C00

#define ALT_K           0x2500
#define ALT_M           0x3200
#define ALT_V           0x2F00

#endif

