
#ifndef _TEST_DEF_H_
#define _TEST_DEF_H_

#define NO_STATUS       0x0000
#define STATUS_OK       0x0001

#define ACBU_TEST       0x01
#define ECBU_TEST       0x02
#define ICU1_TEST       0x03
#define ICU2_TEST       0x04
#define FILE_TEST       0x05
#define MEMO_TEST       0x06
#define STAT_TEST       0x07

#define REQ_LOG_C       0x01
#define REQ_LOG_M       0x02
#define REQ_LOG_S       0x03

#define STAT_BITS_MASK  0x0003

#endif

