EXPORT void get_choice(void);
EXPORT void sel_group(void);
EXPORT void sel_phone(void);
EXPORT void sel_phone_internal(void);
EXPORT void sel_phone_inpartyln(void);
EXPORT void sel_phone_outpartyln(void);
EXPORT void sel_phone_grpconf(void);
EXPORT void sel_opgrp(void);
EXPORT void sel_opgrp_mask(void);
EXPORT void sel_opgrp_ctgroup(void);
EXPORT void sel_opgrp_label(void);
EXPORT void sel_pin(void);
EXPORT void sel_extn(void);
PUBLIC void sel_ecbu(void);
EXPORT void sel_extn_group(void);
EXPORT void sel_extn_mask(void);
EXPORT void sel_extn_selcall(void);
EXPORT void sel_assign(void);
EXPORT void sel_default_op(void);
EXPORT void sel_terminal_grpconf(void);





