EXPORT char	field[MAX_FIELDS][MAX_FIELD_LEN];
EXPORT char	*record[]; 

EXPORT	char	db_vals[MAX_FIELDS][MAX_FIELD_LEN];
EXPORT	char	*db_names[];
EXPORT	char	dbdat[MAX_FIELDS][MAX_FIELD_LEN];


EXPORT FIELD gpflds[1]; 
EXPORT FIELD pnflds[3]; 
EXPORT FIELD bpflds[4]; 
EXPORT FORM forms[2]; 


EXPORT	char	*line_names[]; 
EXPORT	char	line_vals[]; 
EXPORT	char	*alert_names[]; 
EXPORT	char	alert_vals[]; 
EXPORT	char	*time_names[]; 
EXPORT	char	time_vals[]; 
