EXPORT int line_assignment(void);
EXPORT void prev_page(void);
EXPORT void next_page(void);
EXPORT void first_page(void);
EXPORT void last_page(void);
EXPORT void get_group(void);
EXPORT void exit_lineass(void);
EXPORT void cursup(void);
EXPORT void cursdn(void);
EXPORT void curslf(void);
EXPORT void cursrt(void);
EXPORT void add_party(void);
EXPORT void add_line(void);
EXPORT void delete_line(void);
EXPORT void modify_line(void);
EXPORT void move_line(void);
EXPORT unsigned process_passive_key(unsigned);

