/*
	lists.h

	Contains the text and values stored for hard-coded choice lists
	
    System  :  Train Control Command Communication System
    Author  :  Ansa Pty. Ltd. (c) 1991
    Revision:  1.0
*/

/*------LINE TYPES---------------------------------------------------------*/

EXPORT char    *line_names[];
EXPORT char    line_vals[];

/*------CALL STATUS--------------------------------------------------------*/

EXPORT char    *callstat_names[];
EXPORT char    callstat_vals[];

/*------DEFAULT CONTROLLER-------------------------------------------------*/

EXPORT char    *default_names[];
EXPORT char    default_vals[];

/*------CONTROLLERS IN TELEPHONY-------------------------------------------*/

EXPORT char    *conttele_names[];
EXPORT char    conttele_vals[];

/*------CONFIG NUMBER------------------------------------------------------*/

EXPORT char    *config_names[];
EXPORT char    config_vals[];

/*------PERMISSION---------------------------------------------------------*/

EXPORT char    *permission_names[];
EXPORT char    permission_vals[];

/*------CONFERENCE LABEL POSITION------------------------------------------*/

EXPORT char    *confpos_names[];
EXPORT char    confpos_vals[];
