EXPORT void save_primsec_ass(void);
EXPORT void select_a_group(void);
EXPORT int primsec_assignments(void);
EXPORT void msel_phone(void);
EXPORT void get_a_group(void);
EXPORT unsigned process_assign_key(unsigned);
EXPORT void next_assign(void);
EXPORT void previous_assign(void);
EXPORT void save_assign(void);
EXPORT int no_of_operators(char *);
EXPORT void next_config(void);
EXPORT void previous_config(void);


